# Generated by Django 4.2.1 on 2023-12-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl', models.CharField(max_length=100)),
                ('c', models.TextField(blank=True)),
                ('t', models.BinaryField()),
            ],
        ),
    ]
