# Generated by Django 4.2.1 on 2023-12-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_newcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCar',
        ),
    ]
