# Generated by Django 4.2.1 on 2023-12-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_delete_newcar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-time_create'], name='car_car_time_cr_7f8bde_idx'),
        ),
    ]
