# Generated by Django 4.2.1 on 2023-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
    ]
