# Generated by Django 4.2.1 on 2024-01-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'draft'), (1, 'PUBLISHED')], default=0),
        ),
    ]
