# Generated by Django 4.2.1 on 2024-01-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_category_car_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.category'),
        ),
    ]
